# SHA 256 security check against Github repository
#	requires and uses wget. Will need to be included in seed drive or POST_FLIGHT_DIR
#  0 = OFF (NO)
#  1= ON (YES)
REQUIRE_REPO_SHA256_CHECK=0
REPO_SHA256_URI=https://raw.githubusercontent.com/DavidGeeraerts/WPF/master/Windows_Post-Flight_SHA256.txt




IF %REQUIRE_REPO_SHA256_CHECK% EQU 0 IF %LOG_LEVEL_DEBUG% EQU 1 ECHO %ISO_DATE% %TIME% [DEBUG]	VARIABLE: REQUIRE_REPO_SHA256_CHECK: %REQUIRE_REPO_SHA256_CHECK% >> %LOG_LOCATION%\%LOG_FILE%
IF %REQUIRE_REPO_SHA256_CHECK% EQU 0 IF %LOG_LEVEL_INFO% EQU 1 ECHO %ISO_DATE% %TIME% [INFO]	Not required to do a repo SHA256 check. >> %LOG_LOCATION%\%LOG_FILE%
IF %REQUIRE_REPO_SHA256_CHECK% EQU 0 GoTo skipWGet
IF %REQUIRE_REPO_SHA256_CHECK% EQU 1 IF %LOG_LEVEL_INFO% EQU 1 ECHO %ISO_DATE% %TIME% [INFO]	Required to do a repo SHA256 check... >> %LOG_LOCATION%\%LOG_FILE%
IF NOT EXIST %POST_FLIGHT_DIR%\wget.exe IF %LOG_LEVEL_ERROR% EQU 1 ECHO %ISO_DATE% %TIME% [ERROR]	WGET was not found here {%POST_FLIGHT_DIR%}! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT EXIST %POST_FLIGHT_DIR%\wget.exe IF %LOG_LEVEL_ERROR% EQU 1 ECHO %ISO_DATE% %TIME% [ERROR]	WGET not found, aborting required sha256 check! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT EXIST %POST_FLIGHT_DIR%\wget.exe GoTo skipWGet
wget --version 2> nul || IF %LOG_LEVEL_DEBUG% EQU 1 ECHO %ISO_DATE% %TIME% [DEBUG]	WGET not found on the computer! >> %LOG_LOCATION%\%LOG_FILE%
IF EXIST %POST_FLIGHT_DIR%\wget.exe IF %LOG_LEVEL_DEBUG% EQU 1 ECHO %ISO_DATE% %TIME% [DEBUG]	WGET was found here: {%POST_FLIGHT_DIR%}! >> %LOG_LOCATION%\%LOG_FILE%

IF DEFINED REPO_SHA256_URI IF %LOG_LEVEL_DEBUG% EQU 1 ECHO %ISO_DATE% %TIME% [DEBUG]	VARIABLE: REPO_SHA256_URI: {%REPO_SHA256_URI%} >> %LOG_LOCATION%\%LOG_FILE%
IF %LOG_LEVEL_INFO% EQU 1 ECHO %ISO_DATE% %TIME% [INFO]	Attemtping to retrieve SHA256 from GitHub repo... >> %LOG_LOCATION%\%LOG_FILE%
IF EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" IF %LOG_LEVEL_WARN% EQU 1 ECHO %ISO_DATE% %TIME% [WARN]	An existing SHA256 repo file exists. It will be deleted! >> %LOG_LOCATION%\%LOG_FILE%
IF EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" del /F /Q "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt"
IF NOT EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" IF %LOG_LEVEL_DEBUG% EQU 1 ECHO %ISO_DATE% %TIME% [DEBUG]	File {GitHub_WPF_SHA256.txt} just got deleted! >> %LOG_LOCATION%\%LOG_FILE%
wget %REPO_SHA256_URI% --output-document=%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt
IF EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" IF %LOG_LEVEL_INFO% EQU 1 ECHO %ISO_DATE% %TIME% [INFO]	Successfully downloaded GitHub SHA256 from WPF repo! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" IF %LOG_LEVEL_ERROR% EQU 1 ECHO %ISO_DATE% %TIME% [ERROR]	Failed to download GitHub SHA256 from WPF repo! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" IF %LOG_LEVEL_ERROR% EQU 1 ECHO %ISO_DATE% %TIME% [ERROR]	Aborting required sha256 check against repo! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT EXIST "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt" GoTo skipWGet
SET /P WPF_REPO_SHA256= < "%POST_FLIGHT_DIR%\GitHub_WPF_SHA256.txt"
IF DEFINED WPF_REPO_SHA256 IF %LOG_LEVEL_DEBUG% EQU 1 ECHO %ISO_DATE% %TIME% [DEBUG]	VARIABLE: WPF_REPO_SHA256: {%WPF_REPO_SHA256%} >> %LOG_LOCATION%\%LOG_FILE%
IF NOT DEFINED WPF_REPO_SHA256 IF %LOG_LEVEL_ERROR% EQU 1 ECHO %ISO_DATE% %TIME% [ERROR]	Failed to create variable WPF_REPO_SHA256! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT DEFINED WPF_REPO_SHA256 IF %LOG_LEVEL_ERROR% EQU 1 ECHO %ISO_DATE% %TIME% [ERROR]	Aborting required sha256 check against repo! >> %LOG_LOCATION%\%LOG_FILE%
IF NOT DEFINED WPF_REPO_SHA256 GoTo skipWGet
IF "%WPF_REPO_SHA256%"=="%WPF_SHA256_CHECK%" (IF %LOG_LEVEL_INFO% EQU 1 ECHO %ISO_DATE% %TIME% [INFO]	WPF seed matches repo SHA256! >> %LOG_LOCATION%\%LOG_FILE%) ELSE (
	IF %LOG_LEVEL_WARN% EQU 1 ECHO %ISO_DATE% %TIME% [WARN]	WPF seed DO NOT match repo SHA256! >> %LOG_LOCATION%\%LOG_FILE%
	)
IF NOT "%WPF_REPO_SHA256%"=="%WPF_SHA256_CHECK%" GoTo err06